version: "3.8"
services:

  db:
    image: "postgres:14.6"
    ports:
      - "5432:5432"
    volumes:
      - ~/.pgdata/base:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=base

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOSTNAME: db
        DB_USER: dbuser
        DB_PASSWORD: dbpassword
    ports:
      - "8080:8080"
    depends_on:
      - db
