server:
  port: 8080
  servlet:
    context-path: /capitole-test

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base
    jdbc-url: jdbc:postgresql://localhost:5432/base
    username: dbuser
    password: dbpassword
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    enabled: true
    clean-disabled: false
