server:
  port: 8080
  servlet:
    context-path: /base

spring:
  datasource:
    url: jdbc:h2:mem:base;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: dbuser
    password: dbpassword
    driverClassName: org.h2.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    clean-disabled: false
